language: java
install: mvn install --quiet -DskipTests=true -B
script: mvn test --quiet -B
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
